artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sumitwatkar/Main-Branching/raw/main/fraud.zip
  local_data_file: artifacts/data_ingestion/fraud.zip
  unzip_dir: artifacts/data_ingestion